HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1039d3410>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1039ae390>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103963350>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103970f90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103973450>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1039819d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103971f90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1039700d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1030ee710>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10326d690>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10320b6d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103218c90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10321b0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103281650>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103219c50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1031f7f10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102db3690>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f15d50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f44b50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ee5a50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ee7ed0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ef2410>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ee6650>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ee4190>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f73e10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f41c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f702d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f61f50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f1c3d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f1e950>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f71190>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f63010>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107064350>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107066390>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106fd0450>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107064c90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10703fb10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10703c1d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10704de10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106fd2310>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106df4c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106df78d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106df4dd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f41590>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f40c50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f1cad0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f43010>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f41050>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f01b90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f03c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f55d10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f03950>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f01650>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f55950>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f57c50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f6dd50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1104d6f90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1104ca390>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110467e10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1104749d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110476e90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1104c1450>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110475550>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1101b1550>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103cf7d10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103cd3150>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103cd0d10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103d05e10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103cac290>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103cae790>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103cd0ed0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103cd3f90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10593a510>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10593ae90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105938990>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105909a10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10590be90>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105916390>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10590a550>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105908b10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034c7f10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103495fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034c47d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103465950>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103467e10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034763d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103466390>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1034645d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1080d7d10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1080ad8d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1080630d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108075810>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108077d10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108086210>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108076610>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108074a50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1081b3c50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108101c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108103c50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1081b0e50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10811ae10>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1081934d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108100ad0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1081c9c50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1081d1910>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107c91910>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107ca4390>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107c9fe50>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107c9d890>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107cc30d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107c9e810>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPConnectionPool(host='localhost', port=40): Max retries exceeded with url: /book (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107ca6b50>: Failed to establish a new connection: [Errno 61] Connection refused'))
